import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 
df = sns.load_dataset('titanic') 
print("Shape:", df.shape) 
print("\nColumns:\n", df.columns.tolist()) 
print("\nData Types:\n", df.dtypes) 
print("\nMissing Values:\n", df.isnull().sum()) 
print("\nSummary:\n", df.describe(include='all')) 
plt.figure(figsize=(6, 4)) 
sns.countplot(data=df, x='survived', palette='Set2') 
plt.title("Survival Count") 
plt.xticks([0, 1], ['Not Survived', 'Survived']) 
plt.show() plt.figure(figsize=(6, 4)) 
sns.countplot(data=df, x='sex', hue='survived', palette='pastel') 
plt.title("Survival by Sex") 
plt.legend(['Not Survived', 'Survived']) 
plt.show() plt.figure(figsize=(6, 4)) 
sns.countplot(data=df, x='pclass', hue='survived', palette='coolwarm') 
plt.title("Survival by Passenger Class") 
plt.show() 
plt.figure(figsize=(10, 5)) 
sns.histplot(df['age'].dropna(), kde=True, bins=30, color='skyblue') plt.title("Age Distribution of 
Passengers") 
plt.xlabel("Age") 
plt.show() plt.figure(figsize=(10, 6)) 
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='Blues') 
plt.title("Feature Correlation") 
plt.show() plt.figure(figsize=(10, 5)) 
sns.boxplot(data=df, x='pclass', y='age', hue='survived', palette='muted') 
plt.title("Age by Class and Survival") 
plt.show()
