import seaborn as sns
import matplotlib.pyplot as plt
tips = sns.load_dataset("tips")
sns.set(style="whitegrid")
plt.figure(figsize=(6, 4))
sns.scatterplot(x="total_bill", y="tip", hue="sex", data=tips)
plt.title("Scatter Plot: Total Bill vs Tip")
plt.show()
plt.figure(figsize=(6, 4))
sns.barplot(x="day", y="total_bill", data=tips, ci=None, palette="muted")
plt.title("Bar Plot: Avg Total Bill by Day")
plt.show()
plt.figure(figsize=(6, 4))
sns.histplot(tips["total_bill"], bins=20, kde=True, color='skyblue')
plt.title("Histogram: Total Bill Distribution")
plt.show()
plt.figure(figsize=(6, 4))
sns.boxplot(x="day", y="tip", data=tips, palette="Set2")
plt.title("Box Plot: Tips by Day")
plt.show()
plt.figure(figsize=(6, 4))
corr = tips.corr()
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Heatmap: Correlation Matrix")
plt.show()
